# Generated by Django 5.2.5 on 2025-09-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
